name = "jurig"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "jurig.sandiasun.biz.id"
custom_domain = true
[[routes]]
pattern = "support.vidio.com.jurig.sandiasun.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.jurig.sandiasun.biz.id"
custom_domain = true
[[routes]]
pattern = "npca.netflix.com.jurig.sandiasun.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.jurig.sandiasun.biz.id"
custom_domain = true

[vars]
PROXYIP = "128.199.171.100:8443"
UUID = "069e3034-f7a5-42d4-9114-b75dda87975f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
