name = "sgdo9"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "sandiasun.biz.id"
custom_domain = true

[vars]
PROXYIP = "152.42.172.170:8443"
UUID = "069e3034-f7a5-42d4-9114-b75dda87975f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
