name = "ibuelbarUS"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "159.65.193.114"
UUID = "abd1a7c2-874e-46eb-bca0-e6d85746f54c"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
